#! /bin/bash
#
# .-----------------------------------------------------------------------.
# | .-------------------------------------------------------------------. |
# | | In this script we will spatially normalize the anatomical dataset | |
# | | into MNI space, we will also use the same transformation to       | |
# | | normalize the BOLD dataset into the MNI space.                    | |
# | |___________________________________________________________________| |
# |_______________________________________________________________________|
#
# Notes:
# 1. Do not put spaces before line continuation character when you're splitting
#    paths
#
# Define yout own working directory
# Note: Whenver you define a directory in a variable, it should not end with
# the '/' character
WORKING_DIR=${HOME}/Functional_Connectivity/Processed_Data/Normalized_Data

# Create an array with the names of the directory in which the data for healthy
# controls and majorly depressed patient are stored.
CATEGORIES=(HC MDD)

# Define the path in which the MNI_Template/atlas will be stored. This
# directory will be create if it doesn't exist.
MNI_Template="${HOME}/Functional_Connectivity/Processed_Data/"\
"Normalized_Data/MNI_Atlas"

############################################################################
# Atlases are downloaded during AFNI installation. To find the location of #
# the atlases run `afni_system_check.py -check_all | grep atlas`. If the   #
# atlases were not downloaded; download them from https://bit.ly/3BpKN2K   #
# Once the tarball has been extracted and placed into whichever location   #
# the afni binaries are stored in, they are immediately available for use. #
############################################################################

if ! [ -d "${MNI_Template}" ]
then
    mkdir -p ${MNI_Template}
fi

# Create a symbolic link for the atlas you want to use.
# For spatial normalization into MNI space, we will use MNI_avg152T1+tlrc
# atals.

ln -sf /opt/afni/MNI_avg152T1+tlrc.* ${MNI_Template}/

# Change into the working directory if it exists
if [ -d "${WORKING_DIR}" ]
then
    pushd ${WORKING_DIR}
else
    echo "${WORKING_DIR}: doesn't exist"
    exit 111;
fi

# Use a nested loop to get into the directory for each subject of each category

for CATEGORY in "${CATEGORIES[@]}"
do
    pushd ${CATEGORY}

    for SUBJECT in $(ls)
    do

        # Grab the SUBJECT_ID
        # Subjects are stored in NORM-SUBJECT_ID
        # Split NORM-SUBJECT_ID at the delimiter and return the specified
        # field
        SUBJECT_ID=$(echo "${SUBJECT}" | cut --delimiter '-' --fields 2)

        pushd ${SUBJECT}

        ###########################################################
        # Spatially normalize the anatomical dataset to MNI space #
        ###########################################################

        # Uniformly distribute the white matter in the brain tissue.

        3dUnifize -prefix BOLD-${SUBJECT_ID}-EC-T1                    \
            -input ANAT-${SUBJECT_ID}.nii

        # Remove the skull and extract the brain tissue from T1-weighted MR
        # image.

        3dSkullStrip -prefix ${SUBJECT_ID}-T1-NoSkull                 \
            -input BOLD-${SUBJECT_ID}-EC-T1+tlrc.

        # Shift the center of DSET to the center of BASE. '_shft' will be
        # appended at the end of DSET. Use the center of mass of the volume as
        # the center (By default, center is the center of volume's grid).

        @Align_Centers -cm                                            \
            -base ${SUBJECT_ID}-BOLD-EC-base+orig.                    \
            -dset ${SUBJECT_ID}-T1-NoSkull+tlrc.

        # Linearly align the anatomical dataset with the EPI dataset. The
        # EPI dataset cab be the functional-MR image. The -epi_base option
        # specifies the starting sub-brick for the alignment.

        align_epi_anat.py -anat ${SUBJECT_ID}-T1-NoSkull_shft+tlrc.   \
            -epi ${SUBJECT_ID}-BOLD-EC-base+orig.                     \
            -epi_base 0                                               \
            -suffix _alBOLDEC                                         \
            -anat_has_skull no                                        \
            -epi_strip 3dAutomask                                     \
            -volreg off                                               \
            -tshift off                                               \
            -resample off

        # Shift (roughly) the center of the aligned anatomical dataset with the
        # standard template in the MNI space. The transformation information
        # will be stored in the base image of BOLD data as well.
        # Again, "_shft" will be appended to the DSET and CHILD.

        @Align_Centers -base ${MNI_Template}/MNI_avg152T1+tlrc.       \
            -dset  ${SUBJECT_ID}-T1-NoSkull_shft_alBOLDEC+tlrc.       \
            -child ${SUBJECT_ID}-BOLD-EC-base+orig.

        # Align SOURCE to BASE and save the transformation matrix for each
        # sub-brick into a 1D file. The cost function that defines the matching
        # between SOURCE and BASE is the lpa (Local Pearson Correlation Abs).
        # Also comput a weight function using 3dAutomask alogrithm plus some
        # blurring of the base image.

        3dAllineate -prefix ${SUBJECT_ID}-T1_to_T1_Allineate          \
            -base ${MNI_Template}/MNI_avg152T1+tlrc.                  \
            -source ${SUBJECT_ID}-T1-NoSkull_shft_alBOLDEC_shft+tlrc. \
            -1Dmatrix_save T1_to_T1_Allineate.aff12.1D                \
            -source_automask                                          \
            -cost lpa                                                 \
            -autoweight                                               \
            -cmass

        # Compute a non-linearly warped version of SOURCE dataset to match the
        # BASE dataset. Gaussian blur the SOURCE and BASE before doing the
        # alignmnet. By default, the blur values is 2.345 (for no good reason).
        # Set the blur values to 0 if you do not want to blur the inputs.

        3dQwarp -prefix T1-NoSkull_shft_alBOLDEC_shft                 \
            -blur 0 0                                                 \
            -base ${MNI_Template}/MNI_avg152T1+tlrc.                  \
            -source ${SUBJECT_ID}-T1_to_T1_Allineate+tlrc

        # So, the 3dcopy command seems to overwrite one of the files created
        # above. The old file needs to be deleted for 3dcopy to execute.
        # ${SUBJECT_ID}-T1-NoSkull_shft_alBOLDEC_shft+tlrc.* will be recreated
        # by 3dcopy.
        rm --force ${SUBJECT_ID}-T1-NoSkull_shft_alBOLDEC_shft+tlrc.*

        # Copy one dataset to the other. 3dCopy foo bar copies foo+orig. to
        # bar+orig. and foo+tlrc. to bar+tlrc. This program copies entire
        # datasets and not jsut sub-bricks.
        3dcopy T1-NoSkull_shft_alBOLDEC_shft                          \
            ${SUBJECT_ID}-T1-NoSkull_shft_alBOLDEC_shft

        #####################################################
        # Spatially normalize the BOLD dataset to MNI space #
        #####################################################

        # Create a copy of the original volume registartion mask.
        3dcopy ${SUBJECT_ID}-BOLD-EC-volreg-mask+orig.                \
            ${SUBJECT_ID}-BOLD-EC-volreg-mask_temp

        # Shift (roughly) the center of the 4D BOLD fMRI data to the space
        # using the same parameters as the base image. The base image has
        # similar alignmnet as the anatomical image. (As explained earlier).
        @Align_Centers -cm                                            \
            -base ${SUBJECT_ID}-BOLD-EC-base_shft+orig                \
            -dset ${SUBJECT_ID}-BOLD-EC-volreg-mask_temp+orig.

        ## Apply a nonlinear transformation and resample to 3x3x3 mm
        3dNwarpApply -prefix ${SUBJECT_ID}-BOLD-EC-volreg-Nwarp       \
            -source ${SUBJECT_ID}-BOLD-EC-volreg-mask_temp_shft+orig. \
            -nwarp 'T1-NoSkull_shft_alBOLDEC_shft_WARP+tlrc. '\
            'T1_to_T1_Allineate.aff12.1D'

        3dcopy ${SUBJECT_ID}-BOLD-EC-volreg-Nwarp+orig                \
            ${SUBJECT_ID}-BOLD-EC-volreg-Nwarp_Backup

        3drefit -view tlrc ${SUBJECT_ID}-BOLD-EC-volreg-Nwarp+orig

        ##get tissuse-based signal before smooth
        3dDeconvolve -float -polort A                                 \
            -errts ${SUBJECT_ID}-BeforeSmooth-ld                      \
            -bucket BeforeSmooth-bucket                               \
            -input ${SUBJECT_ID}-BOLD-EC-volreg-Nwarp+tlrc.

        3dBandpass -band 0.01 0.08                                    \
            -prefix ${SUBJECT_ID}-BeforeSmooth-ld-bp                  \
            -input ${SUBJECT_ID}-BeforeSmooth-ld+tlrc

        # Spatial smoothing with 6 mm FWHM. The value for FWHM is adjustable
        3dmerge -doall                                                \
            -1blur_fwhm 6                                             \
            -prefix ${SUBJECT_ID}-BOLD-EC-volreg-Nwarp-blur6          \
            ${SUBJECT_ID}-BOLD-EC-volreg-Nwarp+tlrc

        # Linear detrending
        3dDeconvolve -float -polort A                                 \
            -bucket bucket                                            \
            -errts ${SUBJECT_ID}-BOLD-EC-volreg-Nwarp-blur6-ld        \
            -input ${SUBJECT_ID}-BOLD-EC-volreg-Nwarp-blur6+tlrc.

        # temporal filtering band pass 0.01-0.1 Hz
        # you can modify the filter if you you want

        3dBandpass -band 0.01 0.08                                    \
            -prefix ${SUBJECT_ID}-BOLD-EC-volreg-Nwarp-blur6-ld-bp    \
            -input ${SUBJECT_ID}-BOLD-EC-volreg-Nwarp-blur6-ld+tlrc

        gzip *K

        popd

    done

    popd

done

popd;

tree ${WORKING_DIR}
